// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhOWK1MvGFMovA9mF3eJtA1gEX-Th1KFs',
    appId: '1:610977525140:web:37df97e24dd779e836b381',
    messagingSenderId: '610977525140',
    projectId: 'note-app-1a334',
    authDomain: 'note-app-1a334.firebaseapp.com',
    storageBucket: 'note-app-1a334.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz7mYeh4KZZ_yYYq8om9XhdWzPirP-BCo',
    appId: '1:610977525140:android:4293c91e23da943b36b381',
    messagingSenderId: '610977525140',
    projectId: 'note-app-1a334',
    storageBucket: 'note-app-1a334.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbpl84XF5y7Ob1tS_igJ2cGDwhZV_p8So',
    appId: '1:610977525140:ios:e652413bb802a34736b381',
    messagingSenderId: '610977525140',
    projectId: 'note-app-1a334',
    storageBucket: 'note-app-1a334.appspot.com',
    iosClientId: '610977525140-6s64bpgvm0l3l9076i3lmb8n5famihv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbpl84XF5y7Ob1tS_igJ2cGDwhZV_p8So',
    appId: '1:610977525140:ios:8f113049762dfdb436b381',
    messagingSenderId: '610977525140',
    projectId: 'note-app-1a334',
    storageBucket: 'note-app-1a334.appspot.com',
    iosClientId: '610977525140-ukqf746go1vk7qcidockghscede1d3rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
